 name: exec
 on:
  # 日本時間9:00～20:00の間、1時間おきに実行する
  # 下記の時刻指定は協定世界時(UTC)になっていることに注意。
  #schedule:
  #  - cron: '0 0-11 * * *'
  workflow_dispatch:
 env:
   BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
   TWITTER_API_KEY: ${{secrets.TWITTER_API_KEY}}
   TWITTER_API_SECRET: ${{secrets.TWITTER_API_SECRET}}
   TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
   TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
 jobs:
   build:
     name: exec
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: pip3 install -r requirements.txt
       - run: python3 suke8.py
